# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
# IP: The module: 'fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.gen/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.gen/sources_1/ip/fifo_generator_1/fifo_generator_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.gen/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
# IP: The module: 'fifo_generator_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.gen/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.gen/sources_1/ip/fifo_generator_1/fifo_generator_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20251009/PAPILLON_v20251009.gen/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
