# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.srcs/sources_1/ip/gig_ethernet_pcs_pma_2/gig_ethernet_pcs_pma_2.xci
# IP: The module: 'gig_ethernet_pcs_pma_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.gen/sources_1/ip/gig_ethernet_pcs_pma_2/gig_ethernet_pcs_pma_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.gen/sources_1/ip/gig_ethernet_pcs_pma_2/synth/gig_ethernet_pcs_pma_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.gen/sources_1/ip/gig_ethernet_pcs_pma_2/synth/gig_ethernet_pcs_pma_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.srcs/sources_1/ip/gig_ethernet_pcs_pma_2/gig_ethernet_pcs_pma_2.xci
# IP: The module: 'gig_ethernet_pcs_pma_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.gen/sources_1/ip/gig_ethernet_pcs_pma_2/gig_ethernet_pcs_pma_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.gen/sources_1/ip/gig_ethernet_pcs_pma_2/synth/gig_ethernet_pcs_pma_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daq/Desktop/PAPILLON_asai/PAPILLON_v20260115/PAPILLON_v20260115.gen/sources_1/ip/gig_ethernet_pcs_pma_2/synth/gig_ethernet_pcs_pma_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
